# Generated by Django 4.1.5 on 2023-01-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Home_title', models.CharField(blank=True, max_length=225, null=True)),
                ('Home_tagline', models.CharField(blank=True, max_length=225, null=True)),
                ('Home_button', models.CharField(blank=True, max_length=225, null=True)),
                ('Home_button_link', models.CharField(blank=True, max_length=225, null=True)),
                ('Home_bgimg', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('HIW_title', models.CharField(blank=True, max_length=225, null=True)),
                ('HIW_tagline', models.CharField(blank=True, max_length=225, null=True)),
                ('Experts_title', models.CharField(blank=True, max_length=225, null=True)),
                ('Experts_tagline', models.CharField(blank=True, max_length=225, null=True)),
                ('Rev_title', models.CharField(blank=True, max_length=225, null=True)),
                ('Rev_tagline', models.CharField(blank=True, max_length=225, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
