# Generated by Django 4.1.5 on 2023-01-24 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_homeblog_title_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogimage',
            name='createdAt',
        ),
    ]
