# Generated by Django 4.1.5 on 2023-01-27 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_homeblog_blog_options_homeblog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsite',
            name='foot_copyright',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.CreateModel(
            name='HomeBlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=225, null=True)),
                ('description', models.CharField(blank=True, max_length=225, null=True)),
                ('image', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='homepage',
            name='Blog_articles',
            field=models.ManyToManyField(blank=True, to='main.homeblogarticle'),
        ),
    ]
