# Generated by Django 4.1.5 on 2023-01-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_mainsite_foot_copyright_homeblogarticle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=225)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='homestep',
            name='icon_color',
        ),
        migrations.RemoveField(
            model_name='homestep',
            name='icon_color_bg',
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(blank=True, default='/placeholder.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, default='/placeholder.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='star',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='homeblog',
            name='blog_options',
            field=models.CharField(blank=True, choices=[('1', 'Simple Blog'), ('2', 'Blog with product cards')], default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='homeblog',
            name='description',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='homeblog',
            name='title',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='homeblog',
            name='title_direction',
            field=models.CharField(blank=True, choices=[('1', 'Left'), ('2', 'Right')], default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='homeblogarticle',
            name='description',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='homeblogarticle',
            name='image',
            field=models.ImageField(blank=True, default='/placeholder.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='homeblogarticle',
            name='title',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='homecategory',
            name='icon',
            field=models.ImageField(blank=True, default='/placeholder.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='homecategory',
            name='title',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Experts_tagline',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Experts_title',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='HIW_tagline',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='HIW_title',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Home_bgimg',
            field=models.ImageField(blank=True, default='/placeholder.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Home_button',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Home_button_link',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Home_category',
            field=models.ManyToManyField(blank=True, default='', to='main.homecategory'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Home_tagline',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Home_title',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Rev_reviews',
            field=models.ManyToManyField(blank=True, default='', to='main.homereview'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Rev_tagline',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Rev_title',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='homereview',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='homereview',
            name='image',
            field=models.ImageField(blank=True, default='/placeholder.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='homereview',
            name='name',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='homereview',
            name='profession',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='homereview',
            name='star',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='homestep',
            name='description',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='homestep',
            name='icon',
            field=models.ImageField(blank=True, default='/placeholder.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='homestep',
            name='title',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='mainsite',
            name='facebook_link',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='mainsite',
            name='favicon',
            field=models.ImageField(blank=True, default='/placeholder.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='mainsite',
            name='foot_copyright',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='mainsite',
            name='foot_logo',
            field=models.ImageField(blank=True, default='/placeholder.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='mainsite',
            name='head_logo',
            field=models.ImageField(blank=True, default='/placeholder.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='mainsite',
            name='instagram_link',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='mainsite',
            name='linkin_link',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='mainsite',
            name='title',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='mainsite',
            name='twitter_link',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='mainsite',
            name='youtube_link',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
    ]
