# Generated by Django 4.1.5 on 2023-01-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_mainsite_main_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='content',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
    ]
