# Generated by Django 4.1.5 on 2023-01-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_metadata_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeblog',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
    ]
