# Generated by Django 4.1.5 on 2023-02-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_homeblog_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, default='', max_length=225)),
                ('budget', models.FloatField(blank=True, default=0)),
                ('time', models.CharField(blank=True, default='', max_length=225)),
                ('name', models.CharField(blank=True, default='', max_length=225)),
                ('email', models.CharField(blank=True, default='', max_length=225)),
                ('contact', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=9)),
                ('comment', models.CharField(blank=True, default='', max_length=500)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
