# Generated by Django 4.1.5 on 2023-02-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=9),
        ),
    ]
