# Generated by Django 4.1.5 on 2023-02-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_quotation_budget_alter_quotation_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=225)),
                ('email', models.CharField(blank=True, default='', max_length=225)),
                ('contact', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
